'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowDown, ArrowRight, Github, Linkedin, Mail, Code2, Layers, Cloud, MapPin, Menu, X, Check, Copy, Terminal, Download, ExternalLink } from 'lucide-react';
import { profile, projects, scripts } from '@/data/portfolio';

function ProjectPreview({ type }: { type: string }) {
  const cloud = type === 'hosting';
  const domain = type === 'domain';
  return <div className={'project-art architecture-art '+type} aria-hidden="true"><div className="architecture-top"><span>{cloud?'DEPLOYMENT WORKFLOW':domain?'DOMAIN & SECURITY':'EC2 / WEB SERVER DEPLOYMENT'}</span><span>↗</span></div><div className="architecture-core">{cloud?<Cloud size={37}/>:domain?<Layers size={37}/>:<Terminal size={37}/>}<b>{cloud?'From build to browser.':domain?'A name. A secure connection.':'Linux servers. Live websites.'}</b><span>{cloud?'STATIC FILES. GLOBAL DELIVERY.':domain?'DOMAIN → DNS → HTTPS':'STATIC HOSTING ON AMAZON EC2'}</span></div><div className="architecture-flow">{(cloud?['Build','S3','CloudFront']:domain?['GoDaddy','Route 53','TLS']:['EC2','Nginx','Apache']).map((item,i)=><div key={item}>{i>0&&<ArrowRight size={12}/>}<span>{item}</span></div>)}</div><div className="architecture-bottom"><span>HANDS-ON LEARNING</span><span>{cloud?'02':domain?'03':'01'}</span></div></div>;
}

export default function Home() {
  const [menuOpen,setMenuOpen] = useState(false);
  const [selected,setSelected] = useState<string|null>(null);
  const [copied,setCopied] = useState(false);
  const [copyError,setCopyError] = useState(false);
  async function copyEmail() { try { await navigator.clipboard.writeText(profile.email); setCopied(true); setCopyError(false); setTimeout(()=>setCopied(false),2500); } catch { setCopyError(true); } }
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><a className="logo" href="#" aria-label="Ritik home">{profile.initials}<span>/ portfolio</span></a><nav aria-label="Main navigation" className={menuOpen?'nav open':'nav'}><a href="#work" onClick={()=>setMenuOpen(false)}>Projects</a><a href="#about" onClick={()=>setMenuOpen(false)}>About</a><a href="#scripts" onClick={()=>setMenuOpen(false)}>Shell scripts</a><a href="#skills" onClick={()=>setMenuOpen(false)}>Skills</a><a className="nav-contact" href="#contact" onClick={()=>setMenuOpen(false)}>Let’s talk <ArrowUpRight size={16}/></a></nav><button className="menu-toggle" aria-label={menuOpen?'Close menu':'Open menu'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></header>
    <main id="main">
    <section className="hero container"><div className="hero-copy"><div className="availability"><span/> {profile.available?'Available for opportunities':'Building something new'}</div><p className="intro">Hey, I’m {profile.name} <span className="wave">✳</span></p><h1>Learning DevOps.<br/><span>Building in the cloud.</span></h1><p className="hero-description">An aspiring DevOps engineer, learning by doing.<br/>Exploring AWS, automating everyday tasks, and<br className="desktop-break"/> taking projects from localhost to the cloud.</p><div className="hero-actions"><a className="button primary" href="#work">Explore my work <ArrowUpRight size={18}/></a><a className="text-button" href="#contact">Let’s connect <ArrowRight size={17}/></a></div><div className="hero-meta"><MapPin size={14}/><span>Based in {profile.location}</span><i/> <span>Open to the world</span></div></div><div className="hero-visual"><div className="visual-label"><span>BUILD → AUTOMATE → DEPLOY</span><span>001 / ∞</span></div><div className="code-window"><div className="window-top"><div className="window-dots"><i/><i/><i/></div><span>engineer.ts</span><Code2 size={15}/></div><div className="code-body"><div className="code-line"><small>01</small><code><em>const</em> engineer <em>=</em> {'{'}</code></div><div className="code-line"><small>02</small><code>  name: <strong>'{profile.name}'</strong>,</code></div><div className="code-line"><small>03</small><code>  role: <strong>'Aspiring DevOps engineer'</strong>,</code></div><div className="code-line"><small>04</small><code>  focus: [</code></div><div className="code-line"><small>05</small><code>    <strong>'AWS infrastructure'</strong>,</code></div><div className="code-line"><small>06</small><code>    <strong>'Shell scripting'</strong>,</code></div><div className="code-line"><small>07</small><code>    <strong>'Continuous learning'</strong></code></div><div className="code-line"><small>08</small><code>  ],</code></div><div className="code-line"><small>09</small><code>  curiosity: <em>Infinity</em></code></div><div className="code-line"><small>10</small><code>{'};'}</code></div><div className="code-line empty"><small>11</small></div><div className="code-line"><small>12</small><code><span className="code-comment">// Learning. Building. Improving.</span></code></div><div className="code-line"><small>13</small><code>engineer.<b>deploy</b>();<span className="cursor"/></code></div></div><div className="window-status"><span><span className="tiny-dot"/> Learning in progress</span><span>AWS · Linux · Bash</span></div></div><div className="floating-tag"><span>✳</span> One deployment at a time.</div><div className="visual-caption">CURIOSITY IS MY MOST IMPORTANT TOOL.</div></div></section>
    <div className="stack-strip"><div className="container"><span className="strip-label">MY EVERYDAY TOOLKIT</span>{['AWS','Linux','Bash','Git & GitHub','CloudFront'].map((x,i)=><span key={x} className="stack-item"><span>{['☁','>_','$','⑂','◈'][i]}</span>{x}</span>)}</div></div>
    <section id="work" className="section container"><div className="section-heading"><div><p className="eyebrow">01 — SELECTED WORK</p><h2>Hands-on. Always learning<span>.</span></h2></div><p>My cloud learning journey.<br/>Real skills, built one step at a time.</p></div><div className="projects">{projects.map((p,i)=><article className="project-card" key={p.id}><button className="preview-button" aria-label={`View ${p.name} project details`} onClick={()=>setSelected(selected===p.id?null:p.id)} aria-expanded={selected===p.id} aria-controls={`${p.id}-details`}><ProjectPreview type={p.type}/><span className="preview-arrow"><ArrowUpRight size={20}/></span></button><div className="project-info"><p className="project-category">{p.category}<span>0{i+1}</span></p><h3><button onClick={()=>setSelected(selected===p.id?null:p.id)} aria-expanded={selected===p.id} aria-controls={`${p.id}-details`}>{p.name}<ArrowUpRight size={22}/></button></h3><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div>{p.proofUrl&&<a className="project-proof" href={p.proofUrl} target="_blank" rel="noopener noreferrer"><Linkedin size={16}/> View deployment on LinkedIn <ArrowUpRight size={15}/></a>}{selected===p.id&&<div className="project-details" id={`${p.id}-details`}><b>{p.sample ? "Learning focus" : "Hands-on experience"}</b><p>{p.detail}</p>{p.url&&<a href={p.url} target="_blank" rel="noreferrer">Visit project <ExternalLink size={14}/></a>}{p.github&&<a href={p.github} target="_blank" rel="noreferrer">Source code <Github size={14}/></a>}</div>}</div></article>)}</div><p className="sample-note">Learning portfolio · Project visuals illustrate the workflow; they are not production screenshots.</p></section>
    <section id="scripts" className="section container scripts-section"><div className="section-heading"><div><p className="eyebrow">AUTOMATE THE EVERYDAY</p><h2>Small scripts. Useful <span>impact.</span></h2></div><p>My shell scripting practice.<br/>Less repetition. More understanding.</p></div><div className="script-grid">{scripts.map(script=><article className="script-card" key={script.file}><div className="script-title"><Terminal size={21}/><h3>{script.file}</h3><span>BASH</span></div><p>{script.description}</p><div className="script-command"><span>$</span> {script.command}<span className="script-comment"># command preview</span></div><footer><span>{script.focus}</span><a href={script.repository} target="_blank" rel="noreferrer">View repository <ArrowUpRight size={15}/></a></footer></article>)}</div></section>
    <section id="about" className="section about-section container"><div className="about-title"><p className="eyebrow">02 — A LITTLE ABOUT ME</p><h2>A fresher’s mindset.<br/><span>An engineer’s curiosity.</span></h2><div className="signature">{profile.name}<span>✳</span></div></div><div className="about-copy"><p>I’m {profile.name}, an aspiring DevOps engineer based in {profile.location}. I’m currently learning DevOps through hands-on practice with AWS, Linux, and shell scripting. I enjoy understanding how a website gets from my computer to a reliable, publicly accessible service.</p><p>I’ve deployed static websites on EC2 using Nginx and Apache, and worked with S3, CloudFront, and Route 53. I also have hands-on experience connecting a GoDaddy domain and setting up TLS for website hosting. I also write shell scripts for backups and health checks. I’m looking for a fresher or internship opportunity where I can contribute, ask good questions, and keep growing.</p><div className="about-values"><span><Code2 size={18}/> Hands-on cloud practice</span><span><Layers size={18}/> Ready to learn & contribute</span></div>{profile.resume&&<a className="text-button" href={profile.resume} download>Download résumé <Download size={16}/></a>}</div></section>
    <section id="skills" className="section container skills-section"><div className="section-heading"><div><p className="eyebrow">03 — WHAT I WORK WITH</p><h2>My growing DevOps toolkit<span>.</span></h2></div></div><div className="skills-grid">{[{icon:Cloud,title:'AWS & cloud',desc:'Hands-on practice with hosting and infrastructure.',items:['Amazon S3','CloudFront','EC2','Route 53']},{icon:Terminal,title:'Linux & automation',desc:'Learning to make everyday operations repeatable.',items:['Linux','Bash','Shell scripting','Git & GitHub']},{icon:Code2,title:'Domains & delivery',desc:'Connecting a website to the outside world.',items:['Nginx','Apache','DNS','GoDaddy domains','TLS / HTTPS','Static hosting']}].map(group=><div className="skill-card" key={group.title}><group.icon size={24}/><h3>{group.title}</h3><p>{group.desc}</p><div className="tags">{group.items.map(x=><span key={x}>{x}</span>)}</div></div>)}</div></section>
    <section id="contact" className="container contact-section"><div className="contact-top"><p className="eyebrow">04 — SAY HELLO</p><span>GOOD THINGS START WITH A CONVERSATION</span></div><div className="contact-main"><div><h2>Looking for a curious fresher?<br/>Let’s <span>connect.</span></h2><p>Open to DevOps internships, entry-level roles, and opportunities to learn with a team.</p></div><a className="contact-circle" href={profile.email?`mailto:${profile.email}`:'#contact-details'} aria-label="Get in touch"><ArrowUpRight/></a></div><div className="contact-bottom" id="contact-details">{profile.email?<div className="email-row"><a href={`mailto:${profile.email}`}>{profile.email}</a><button onClick={copyEmail} aria-label="Copy email address">{copied?<Check size={18}/>:<Copy size={18}/>}</button><span role="status">{copied?'Copied!':copyError?'Please select and copy the email.':''}</span></div>:<p className="contact-placeholder"><Mail size={18}/> Your next collaboration starts here.<small>Add your email in data/portfolio.ts to connect.</small></p>}<div className="social-links">{profile.github&&<a href={profile.github} target="_blank" rel="noreferrer"><Github size={17}/>GitHub<ArrowUpRight size={14}/></a>}{profile.linkedin&&<a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={17}/>LinkedIn<ArrowUpRight size={14}/></a>}</div></div></section>
    </main><footer className="site-footer container"><a href="#" className="logo">{profile.initials}</a><p>© {new Date().getFullYear()} {profile.name}. Learning, one deployment at a time.</p><a href="#">Back to top <ArrowDown size={14} className="up-arrow"/></a></footer>
  </>;
}
